version: '3.8'
services:
  # app service for your backend
  app:
    container_name: backend-socket
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: chatDB
      DATABASE_USER: server
      DATABASE_PASS: serverPA2423423
      DATABASE_URI:  mongodb://database:27017
    ports:
      - '3000:3000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatDB
      MONGO_INITDB_ROOT_PASSWORD: serverPA2423423